#' Simulated Cell Type Labels for osmFISH Dataset
#'
#' A named character vector containing simulated single-cell level cell type annotations
#' used in the SpaPheno osmFISH example. Each element name corresponds to a unique cell ID.
#'
#' @format A named character vector with length equal to the number of cells (e.g., 6000+).
#' Names are cell IDs, values are cell type names (e.g., "Neuron", "Astrocyte", etc.).
#'
#' @source Simulated using cell type annotation from synthetic osmFISH data.
"osmFISH_metadata_cellType"

#' Simulated Region Labels for osmFISH Dataset
#'
#' A named character vector containing spatial region annotations for cells in the simulated
#' osmFISH dataset. Each element corresponds to the region label assigned to a cell.
#'
#' @format A named character vector with length matching the number of cells.
#' Names are cell IDs, and values represent spatial region names (e.g., "Region1", "Region2").
#'
#' @source Simulated spatial region assignment in osmFISH synthetic dataset.
"osmFISH_metadata_region"

#' Simulated Phenotype Labels for osmFISH Dataset
#'
#' A character vector containing the names of two spatial regions used as simulated binary phenotypes
#' in the osmFISH synthetic dataset. These phenotype labels define the two groups (e.g., "Tumor" vs "Normal")
#' for training and evaluating spatially-informed predictive models.
#'
#' @format A character vector of length 2. Each element is the name of a region selected from
#' the `osmFISH_metadata_region` object. These two regions are used to simulate binary phenotypic classes.
#'
#' @usage data(osmFISH_phenotype_simu)
#'
#' @seealso \code{\link{osmFISH_metadata_region}}, \code{\link{generate_simulated_bulk_data}}
#'
#' @examples
#' data(osmFISH_phenotype_simu)
#' print(osmFISH_phenotype_simu)
#'
#' @source Extracted from simulated osmFISH region labels in the SpaPheno tutorial.
"osmFISH_phenotype_simu"

#' Simulated Pseudo-Bulk Deconvolved Cell Type Compositions (osmFISH)
#'
#' A matrix representing simulated pseudo-bulk deconvolution results, where each row
#' corresponds to a bulk sample and each column represents a cell type proportion.
#'
#' @format A numeric matrix of dimensions 100 x N (e.g., 100 bulk samples × 20 cell types).
#' Row names are pseudo-bulk sample IDs, column names are cell type names.
#'
#' @source Generated by `generate_simulated_bulk_data()` using simulated osmFISH single-cell input.
"osmFISH_bulk_decon"

#' Simulated Phenotypic Labels for Pseudo-Bulk Samples (osmFISH)
#'
#' A named numeric vector containing binary phenotypic labels (e.g., 0/1) for each pseudo-bulk sample.
#' These labels are used as the target variable for phenotype prediction models.
#'
#' @format A named numeric vector of length 100. Names are sample IDs, values are binary phenotype labels.
#'
#' @source Simulated phenotype assignment from spatial region groups in osmFISH synthetic data.
"osmFISH_bulk_pheno"

#' Spatial Coordinates for Simulated Bulk Samples (osmFISH)
#'
#' A data frame containing spatial (X, Y) coordinates for each cell or spot in the simulated
#' osmFISH dataset. These coordinates are used for mapping spatial distributions, computing
#' neighborhood features, and visualizing predicted phenotypic risk across the tissue.
#'
#' @format A data frame with rows corresponding to cells or spatial units and two columns:
#' \describe{
#'   \item{X}{The horizontal spatial coordinate.}
#'   \item{Y}{The vertical spatial coordinate.}
#' }
#' Row names are unique cell or spot identifiers and match those used in the associated
#' `osmFISH_bulk_decon` and `osmFISH_metadata_cellType` objects.
#'
#' @usage data(osmFISH_bulk_coordinate)
#'
#' @seealso \code{\link{osmFISH_bulk_decon}}, \code{\link{osmFISH_metadata_cellType}}
#'
#' @examples
#' data(osmFISH_bulk_coordinate)
#' head(osmFISH_bulk_coordinate)
#' plot(osmFISH_bulk_coordinate$X, osmFISH_bulk_coordinate$Y, pch = 20)
#'
#' @source Derived from the spatial layout in the osmFISH simulation dataset used in SpaPheno.
"osmFISH_bulk_coordinate"
